In [1]:
import pandas as pd
import glob
import shutil
import sys
import numpy as np

In [2]:
# Manual cleaning
    # Removed "Loans that do not meet credit policy"
    # Removed all the lines beginning with "Total amount"
    # All the empty cells made 0
    # Remove first line from all the CSVs. There is some comment.

In [3]:
# Load all the csv files.
loan_data = pd.DataFrame()
for file in glob.glob("Loan*.csv"):
    print(file)
    df = pd.read_csv(file, dtype={'id':float,  # 0
                                  'member_id':float,  # 1
                                  'loan_amnt':int,  # 2
                                  'funded_amnt':int,  # 3
                                  'funded_amnt_inv':str,  # 4
                                  'term':str,  # 5
                                  'int_rate':str,  # 6
                                  'installment':float,  # 7
                                  'grade':str,  # 8
                                  'sub_grade':str,  # 9
                                  'emp_title':str,  # 10
                                  'emp_length':str,  # 11
                                  'home_ownership':str,  # 12
                                  'annual_inc':str,  # 13
                                  'verification_status':str,  # 14
                                  'issue_d':str,  # 15
                                  'loan_status':str,  # 16
                                  'pymnt_plan':str,  # 17
                                  'url':str,  # 18
                                  'desc':str,  # 19
                                  'purpose':str,  # 20
                                  'title':str,  # 21
                                  'zip_code':str,  # 22
                                  'addr_state':str,  # 23
                                  'dti':float,  # 24
                                  'delinq_2yrs':int,  # 25
                                  'earliest_cr_line':str,  # 26
                                  'inq_last_6mths':int,  # 27
                                  'mths_since_last_delinq':float,  # 28
                                  'mths_since_last_record':float,  # 29
                                  'open_acc':int,  # 30
                                  'pub_rec':int,  # 31
                                  'revol_bal':int,  # 32
                                  'revol_util':str,  # 33
                                  'total_acc':int,  # 34
                                  'initial_list_status':str,  # 35
                                  'out_prncp':float,  # 36
                                  'out_prncp_inv':float,  # 37
                                  'total_pymnt':float,  # 38
                                  'total_pymnt_inv':float,  # 39
                                  'total_rec_prncp':float,  # 40
                                  'total_rec_int':float,  # 41
                                  'total_rec_late_fee':float,  # 42
                                  'recoveries':float,  # 43
                                  'collection_recovery_fee':float,  # 44
                                  'last_pymnt_d':str,  # 45
                                  'last_pymnt_amnt':float,  # 46
                                  'next_pymnt_d':str,  # 47
                                  'last_credit_pull_d':str,  # 48
                                  'collections_12_mths_ex_med':int,  # 49
                                  'mths_since_last_major_derog':float,  # 50
                                  'policy_code':int,  # 51
                                  'application_type':str,  # 52
                                  'annual_inc_joint':float,  # 53
                                  'dti_joint':float,  # 54
                                  'verification_status_joint':str,  # 55
                                  'acc_now_delinq':int,  # 56
                                  'tot_coll_amt':float,  # 57
                                  'tot_cur_bal':float,  # 58
                                  'open_acc_6m':float,  # 59
                                  'open_act_il':float,  # 60
                                  'open_il_12m':float,  # 61
                                  'open_il_24m':float,  # 62
                                  'mths_since_rcnt_il':float,  # 63
                                  'total_bal_il':float,  # 64
                                  'il_util':float,  # 65
                                  'open_rv_12m':float,  # 66
                                  'open_rv_24m':float,  # 67
                                  'max_bal_bc':float,  # 68
                                  'all_util':float,  # 69
                                  'total_rev_hi_lim':float,  # 70
                                  'inq_fi':float,  # 71
                                  'total_cu_tl':float,  # 72
                                  'inq_last_12m':float,  # 73
                                  'acc_open_past_24mths':float,  # 74
                                  'avg_cur_bal':float,  # 75
                                  'bc_open_to_buy':float,  # 76
                                  'bc_util':float,  # 77
                                  'chargeoff_within_12_mths':int,  # 78
                                  'delinq_amnt':int,  # 79
                                  'mo_sin_old_il_acct':float,  # 80
                                  'mo_sin_old_rev_tl_op':float,  # 81
                                  'mo_sin_rcnt_rev_tl_op':float,  # 82
                                  'mo_sin_rcnt_tl':float,  # 83
                                  'mort_acc':float,  # 84
                                  'mths_since_recent_bc':float,  # 85
                                  'mths_since_recent_bc_dlq':float,  # 86
                                  'mths_since_recent_inq':float,  # 87
                                  'mths_since_recent_revol_delinq':float,  # 88
                                  'num_accts_ever_120_pd':float,  # 89
                                  'num_actv_bc_tl':float,  # 90
                                  'num_actv_rev_tl':float,  # 91
                                  'num_bc_sats':float,  # 92
                                  'num_bc_tl':float,  # 93
                                  'num_il_tl':float,  # 94
                                  'num_op_rev_tl':float,  # 95
                                  'num_rev_accts':float,  # 96
                                  'num_rev_tl_bal_gt_0':float,  # 97
                                  'num_sats':float,  # 98
                                  'num_tl_120dpd_2m':float,  # 99
                                  'num_tl_30dpd':float,  # 100
                                  'num_tl_90g_dpd_24m':float,  # 101
                                  'num_tl_op_past_12m':float,  # 102
                                  'pct_tl_nvr_dlq':float,  # 103
                                  'percent_bc_gt_75':float,  # 104
                                  'pub_rec_bankruptcies':float,  # 105
                                  'tax_liens':int,  # 106
                                  'tot_hi_cred_lim':float,  # 107
                                  'total_bal_ex_mort':float,  # 108
                                  'total_bc_limit':float,  # 109
                                  'total_il_high_credit_limit':float,  # 110
                                  'revol_bal_joint':float,  # 111
                                  'sec_app_earliest_cr_line':str,  # 112
                                  'sec_app_inq_last_6mths':float,  # 113
                                  'sec_app_mort_acc':float,  # 114
                                  'sec_app_open_acc':float,  # 115
                                  'sec_app_revol_util':float,  # 116
                                  'sec_app_open_act_il':float,  # 117
                                  'sec_app_num_rev_accts':float,  # 118
                                  'sec_app_chargeoff_within_12_mths':float,  # 119
                                  'sec_app_collections_12_mths_ex_med':float,  # 120
                                  'sec_app_mths_since_last_major_derog':float,  # 121
                                  'hardship_flag':str,  # 122
                                  'hardship_type':str,  # 123
                                  'hardship_reason':str,  # 124
                                  'hardship_status':str,  # 125
                                  'deferral_term':float,  # 126
                                  'hardship_amount':float,  # 127
                                  'hardship_start_date':str,  # 128
                                  'hardship_end_date':str,  # 129
                                  'payment_plan_start_date':str,  # 130
                                  'hardship_length':float,  # 131
                                  'hardship_dpd':float,  # 132
                                  'hardship_loan_status':str,  # 133
                                  'orig_projected_additional_accrued_interest':float,  # 134
                                  'hardship_payoff_balance_amount':float,  # 135
                                  'hardship_last_payment_amount':float,  # 136
                                  'disbursement_method':str,  # 137
                                  'debt_settlement_flag':str,  # 138
                                  'debt_settlement_flag_date':str,  # 139
                                  'settlement_status':str,  # 140
                                  'settlement_date':str,  # 141
                                  'settlement_amount':str,  # 142
                                  'settlement_percentage':str,  # 143
                                  'settlement_term':str})
    # df = pd.read_csv(file, dtype={'loan_amnt':int, 'funded_amnt':int, 'funded_amnt_inv':str, 'term':str, 'int_rate':str, 'installment':float, 'grade':str, 'sub_grade':str, 'emp_title':str, 'emp_length':str, 'home_ownership':str, 'annual_inc':str, 'verification_status':str, 'issue_d':str, 'loan_status':str, 'pymnt_plan':str, 'url':str, 'desc':str, 'purpose':str, 'title':str, 'zip_code':str, 'addr_state':str, 'dti':float, 'delinq_2yrs':int, 'earliest_cr_line':str, 'inq_last_6mths':int, 'mths_since_last_delinq':int, 'mths_since_last_record':int, 'open_acc':int, 'pub_rec':int, 'revol_bal':int, 'revol_util':str, 'total_acc':int, 'initial_list_status':str, 'out_prncp':float, 'out_prncp_inv':float, 'total_pymnt':float, 'total_pymnt_inv':float, 'total_rec_prncp':float, 'total_rec_int':float, 'total_rec_late_fee':int, 'recoveries':int, 'collection_recovery_fee':int, 'last_pymnt_d':str, 'last_pymnt_amnt':float, 'next_pymnt_d':str, 'last_credit_pull_d':str, 'collections_12_mths_ex_med':int, 'mths_since_last_major_derog':int, 'policy_code':int, 'application_type':str, 'annual_inc_joint':int, 'dti_joint':int, 'verification_status_joint':int, 'acc_now_delinq':int, 'tot_coll_amt':int, 'tot_cur_bal':int, 'open_acc_6m':int, 'open_act_il':int, 'open_il_12m':int, 'open_il_24m':int, 'mths_since_rcnt_il':int, 'total_bal_il':int, 'il_util':int, 'open_rv_12m':int, 'open_rv_24m':int, 'max_bal_bc':int, 'all_util':int, 'total_rev_hi_lim':int, 'inq_fi':int, 'total_cu_tl':int, 'inq_last_12m':int, 'acc_open_past_24mths':int, 'avg_cur_bal':int, 'bc_open_to_buy':int, 'bc_util':float, 'chargeoff_within_12_mths':int, 'delinq_amnt':int, 'mo_sin_old_il_acct':int, 'mo_sin_old_rev_tl_op':int, 'mo_sin_rcnt_rev_tl_op':int, 'mo_sin_rcnt_tl':int, 'mort_acc':int, 'mths_since_recent_bc':int, 'mths_since_recent_bc_dlq':int, 'mths_since_recent_inq':int, 'mths_since_recent_revol_delinq':int, 'num_accts_ever_120_pd':int, 'num_actv_bc_tl':int, 'num_actv_rev_tl':int, 'num_bc_sats':int, 'num_bc_tl':int, 'num_il_tl':int, 'num_op_rev_tl':int, 'num_rev_accts':int, 'num_rev_tl_bal_gt_0':int, 'num_sats':int, 'num_tl_120dpd_2m':int, 'num_tl_30dpd':int, 'num_tl_90g_dpd_24m':int, 'num_tl_op_past_12m':int, 'pct_tl_nvr_dlq':float, 'percent_bc_gt_75':float, 'pub_rec_bankruptcies':int, 'tax_liens':int, 'tot_hi_cred_lim':int, 'total_bal_ex_mort':int, 'total_bc_limit':int, 'total_il_high_credit_limit':int, 'revol_bal_joint':int, 'sec_app_earliest_cr_line':int, 'sec_app_inq_last_6mths':int, 'sec_app_mort_acc':int, 'sec_app_open_acc':int, 'sec_app_revol_util':int, 'sec_app_open_act_il':int, 'sec_app_num_rev_accts':int, 'sec_app_chargeoff_within_12_mths':int, 'sec_app_collections_12_mths_ex_med':int, 'sec_app_mths_since_last_major_derog':int, 'hardship_flag':str, 'hardship_type':str, 'hardship_reason':str, 'hardship_status':str, 'deferral_term':int, 'hardship_amount':float, 'hardship_start_date':str, 'hardship_end_date':str, 'payment_plan_start_date':str, 'hardship_length':int, 'hardship_dpd':int, 'hardship_loan_status':str, 'orig_projected_additional_accrued_interest':float, 'hardship_payoff_balance_amount':float, 'hardship_last_payment_amount':float, 'disbursement_method':str, 'debt_settlement_flag':str, 'debt_settlement_flag_date':str, 'settlement_status':str, 'settlement_date':str, 'settlement_amount':str, 'settlement_percentage':str, 'settlement_term':str})
    loan_data = loan_data.append(df)

LoanStats3a.csv
LoanStats3b.csv
LoanStats3c.csv
LoanStats3d.csv
LoanStats_2016Q1.csv
LoanStats_2016Q2.csv
LoanStats_2016Q3.csv
LoanStats_2016Q4.csv
LoanStats_2017Q1.csv
LoanStats_2017Q2.csv
LoanStats_2017Q3.csv
LoanStats_2017Q4.csv


In [4]:
import numpy as np
# Convert all NaN to 0
loan_data.fillna(0, inplace=True)
print(loan_data.shape)

(1765428, 145)


In [5]:
# Delete columns, where all the entries are 0.
loan_data = loan_data.loc[:, (loan_data != 0).any(axis=0)]
print(loan_data.shape)

(1765428, 143)


In [6]:
print(loan_data)

        loan_amnt  funded_amnt funded_amnt_inv        term int_rate  \
0            5000         5000            4975   36 months   10.65%   
1            2500         2500            2500   60 months   15.27%   
2            2400         2400            2400   36 months   15.96%   
3           10000        10000           10000   36 months   13.49%   
4            3000         3000            3000   60 months   12.69%   
5            5000         5000            5000   36 months    7.90%   
6            7000         7000            7000   60 months   15.96%   
7            3000         3000            3000   36 months   18.64%   
8            5600         5600            5600   60 months   21.28%   
9            5375         5375            5350   60 months   12.69%   
10           6500         6500            6500   60 months   14.65%   
11          12000        12000           12000   36 months   12.69%   
12           9000         9000            9000   36 months   13.49%   
13    

In [7]:
# Load the dictionary from Lending Club data
# loan_dict = pd.read_excel(open('LCDataDictionary.xlsx','rb'), sheetname='LoanStats')
loan_dict = pd.read_excel(open('LCDataDictionary.xlsx','rb'), sheet_name='LoanStats')

In [8]:
loan_data.info()
pd.set_option('max_colwidth',1000)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1765428 entries, 0 to 118647
Columns: 143 entries, loan_amnt to settlement_term
dtypes: float64(85), int32(14), object(44)
memory usage: 1.8+ GB


In [9]:
# Now analyze one column at a time
# loan_dict.loc[loan_dict['LoanStatNew'] == 'loan_amnt']
print(loan_data.iloc[:5,:6])
for y in loan_data.columns[:6]:
  print(y, loan_data[y].dtype)
loan_dict.loc[loan_dict['LoanStatNew'].isin(list(loan_data.columns.values[:6]))]

   loan_amnt  funded_amnt funded_amnt_inv        term int_rate  installment
0       5000         5000            4975   36 months   10.65%       162.87
1       2500         2500            2500   60 months   15.27%        59.83
2       2400         2400            2400   36 months   15.96%        84.33
3      10000        10000           10000   36 months   13.49%       339.31
4       3000         3000            3000   60 months   12.69%        67.79
loan_amnt int32
funded_amnt int32
funded_amnt_inv object
term object
int_rate object
installment float64


LoanStatNew  \
23      funded_amnt   
24  funded_amnt_inv   
33      installment   
34         int_rate   
41        loan_amnt   
94             term   

                                                                                                                                                                     Description  
23                                                                                                                The total amount committed to that loan at that point in time.  
24                                                                                                  The total amount committed by investors for that loan at that point in time.  
33                                                                                                              The monthly payment owed by the borrower if the loan originates.  
34                                                                                                                                                     Interest Rate on the loan  
41  The listed amount of the loan applied for by the borrower. If at some point in time, the credit department reduces the loan amount, then it will be reflected in this value.  
94                                                                                          The number of payments on the loan. Values are in months and can be either 36 or 60.

In [10]:
# Analysis
# loan_amnt is int32 - Good
# funded_amnt is int32 - Good
# funded_amnt_inv is object - Bad
# term is object - Bad
# int_rate is object - Bad

# Let's start with funded_amnt_inv
# Find the non-int entry
df = loan_data['funded_amnt_inv'].to_frame().applymap(np.isreal) == False
df.loc[df['funded_amnt_inv'] == True]

funded_amnt_inv
0                  True
1                  True
2                  True
3                  True
4                  True
5                  True
6                  True
7                  True
8                  True
9                  True
10                 True
11                 True
12                 True
13                 True
14                 True
15                 True
16                 True
17                 True
18                 True
19                 True
20                 True
21                 True
22                 True
23                 True
24                 True
25                 True
26                 True
27                 True
28                 True
29                 True
...                 ...
118618             True
118619             True
118620             True
118621             True
118622             True
118623             True
118624             True
118625             True
118626             True
118627             True
118628             True
118629             True
118630             True
118631             True
118632             True
118633             True
118634             True
118635             True
118636             True
118637             True
118638             True
118639             True
118640             True
118641             True
118642             True
118643             True
118644             True
118645             True
118646             True
118647             True

[1765428 rows x 1 columns]

In [11]:
# Looks like all the entries are considered non-integral
# Let's examine
loan_data['funded_amnt_inv'][:1]
# Since each object seems to string, convert it to numeric.
loan_data['funded_amnt_inv'] = pd.to_numeric(loan_data['funded_amnt_inv'])
# Find the non-numeric entry
df = loan_data['funded_amnt_inv'].to_frame().applymap(np.isreal) == False
df.loc[df['funded_amnt_inv'] == True]
df = loan_data['funded_amnt_inv']
df.loc[df.isnull()]
# So now the data for funded_amnt_inv is all good.

Series([], Name: funded_amnt_inv, dtype: float64)

In [12]:
# Moving to "term"
# All terms are described in terms of months.
# So, a simple replacement should work.
loan_data['term'] = loan_data['term'].str.replace(" months","")
# Now convert all of them to numeric
loan_data['term'] = pd.to_numeric(loan_data['term'])
# Find the non-numeric entry
df = loan_data['term'].to_frame().applymap(np.isreal) == False
df.loc[df['term'] == True]
# The term data looks all good.

Empty DataFrame
Columns: [term]
Index: []

In [13]:
# Moving to "int_rate"
# All int_rate are described in terms of %.
# So, a simple replacement should work.
loan_data['int_rate'] = loan_data['int_rate'].str.replace("%","")
# Now convert all of them to numeric
loan_data['int_rate'] = pd.to_numeric(loan_data['int_rate'])
# Find the non-numeric entry
df = loan_data['int_rate'].to_frame().applymap(np.isreal) == False
df.loc[df['int_rate'] == True]
# The int_rate data looks all good.

Empty DataFrame
Columns: [int_rate]
Index: []

In [14]:
# Moving to "installment"
# Find the non-numeric entry
df = loan_data['installment'].to_frame().applymap(np.isreal) == False
df.loc[df['installment'] == True]
# The installment data looks all good.

Empty DataFrame
Columns: [installment]
Index: []

In [15]:
# Print thoese features again
print(loan_data.iloc[:5,:6])
for y in loan_data.columns[:6]:
  print(y, loan_data[y].dtype)

   loan_amnt  funded_amnt  funded_amnt_inv  term  int_rate  installment
0       5000         5000           4975.0    36     10.65       162.87
1       2500         2500           2500.0    60     15.27        59.83
2       2400         2400           2400.0    36     15.96        84.33
3      10000        10000          10000.0    36     13.49       339.31
4       3000         3000           3000.0    60     12.69        67.79
loan_amnt int32
funded_amnt int32
funded_amnt_inv float64
term int64
int_rate float64
installment float64


In [16]:
# Want to see if the loan_amnt and funded_amnt are ever different
df_ = loan_data['loan_amnt'] - loan_data['funded_amnt'] != 0
df = df_.to_frame()
print(len(df.loc[df[0] == True]))

2065


In [17]:
# Since, there are 2065 cases where the loan_amnt and funded_amnt are different I am going to keep both the features.
# 2065 is really small compared to the 1.7 million data we have.
# But, for now, I will keep it.

In [18]:
# Look for 0 loan_amnt
loan_data.drop(loan_data[loan_data.loan_amnt == 0].index, inplace=True)
loan_data.loc[loan_data['loan_amnt'] == 0]

Empty DataFrame
Columns: [loan_amnt, funded_amnt, funded_amnt_inv, term, int_rate, installment, grade, sub_grade, emp_title, emp_length, home_ownership, annual_inc, verification_status, issue_d, loan_status, pymnt_plan, url, desc, purpose, title, zip_code, addr_state, dti, delinq_2yrs, earliest_cr_line, inq_last_6mths, mths_since_last_delinq, mths_since_last_record, open_acc, pub_rec, revol_bal, revol_util, total_acc, initial_list_status, out_prncp, out_prncp_inv, total_pymnt, total_pymnt_inv, total_rec_prncp, total_rec_int, total_rec_late_fee, recoveries, collection_recovery_fee, last_pymnt_d, last_pymnt_amnt, next_pymnt_d, last_credit_pull_d, collections_12_mths_ex_med, mths_since_last_major_derog, policy_code, application_type, annual_inc_joint, dti_joint, verification_status_joint, acc_now_delinq, tot_coll_amt, tot_cur_bal, open_acc_6m, open_act_il, open_il_12m, open_il_24m, mths_since_rcnt_il, total_bal_il, il_util, open_rv_12m, open_rv_24m, max_bal_bc, all_util, total_rev_hi_lim, inq_fi, total_cu_tl, inq_last_12m, acc_open_past_24mths, avg_cur_bal, bc_open_to_buy, bc_util, chargeoff_within_12_mths, delinq_amnt, mo_sin_old_il_acct, mo_sin_old_rev_tl_op, mo_sin_rcnt_rev_tl_op, mo_sin_rcnt_tl, mort_acc, mths_since_recent_bc, mths_since_recent_bc_dlq, mths_since_recent_inq, mths_since_recent_revol_delinq, num_accts_ever_120_pd, num_actv_bc_tl, num_actv_rev_tl, num_bc_sats, num_bc_tl, num_il_tl, num_op_rev_tl, num_rev_accts, num_rev_tl_bal_gt_0, num_sats, num_tl_120dpd_2m, num_tl_30dpd, num_tl_90g_dpd_24m, ...]
Index: []

[0 rows x 143 columns]

In [19]:
# Now analyze the next 5 features
print(loan_data.iloc[:5,6:11])
for y in loan_data.columns[6:11]:
  print(y, loan_data[y].dtype)
loan_dict.loc[loan_dict['LoanStatNew'].isin(list(loan_data.columns.values[6:11]))]

  grade sub_grade                 emp_title emp_length home_ownership
0     B        B2                         0  10+ years           RENT
1     C        C4                     Ryder   < 1 year           RENT
2     C        C5                         0  10+ years           RENT
3     C        C1       AIR RESOURCES BOARD  10+ years           RENT
4     B        B5  University Medical Group     1 year           RENT
grade object
sub_grade object
emp_title object
emp_length object
home_ownership object


LoanStatNew  \
19      emp_length   
20       emp_title   
25           grade   
26  home_ownership   
92       sub_grade   

                                                                                                                                              Description  
19                     Employment length in years. Possible values are between 0 and 10 where 0 means less than one year and 10 means ten or more years.   
20                                                                                    The job title supplied by the Borrower when applying for the loan.*  
25                                                                                                                                 LC assigned loan grade  
26  The home ownership status provided by the borrower during registration or obtained from the credit report. Our values are: RENT, OWN, MORTGAGE, OTHER  
92                                                                                                                              LC assigned loan subgrade

In [20]:
# Starting with grade
loan_data['grade'].unique()

array(['B', 'C', 'A', 'E', 'F', 'D', 'G'], dtype=object)

In [21]:
# 'grade' looks good for a categorical type.
# The 0 corresponds to no data.
# For now, it is ok in out case.

# Next try sub_grade
loan_data['sub_grade'].unique()

array(['B2', 'C4', 'C5', 'C1', 'B5', 'A4', 'E1', 'F2', 'C3', 'B1', 'D1',
       'A1', 'B3', 'B4', 'C2', 'D2', 'A3', 'A5', 'D5', 'A2', 'E4', 'D3',
       'D4', 'F3', 'E3', 'F4', 'F1', 'E5', 'G4', 'E2', 'G3', 'G2', 'G1',
       'F5', 'G5'], dtype=object)

In [22]:
# Again 'sub_grade' looks decent

# Moving to emp_title
print(len(loan_data['emp_title'].unique()))
loan_data['emp_title'].unique()

449772


array(['0', 'Ryder', 'AIR RESOURCES BOARD', ..., 'Acft mechanic',
       'Content Review ', 'BABYSITTER'], dtype=object)

In [23]:
# Too many of them.
# Will drop 'emp_title' from the loan_data for now.
# Will later do some analysis if needed.
loan_data = loan_data.drop('emp_title', 1)

In [24]:
# Moving to emp_length
# First remove "year", "years" and blanks
loan_data['emp_length'] = loan_data['emp_length'].str.replace("years","")
loan_data['emp_length'] = loan_data['emp_length'].str.replace("year","")
loan_data['emp_length'] = loan_data['emp_length'].str.replace(" ","")
print(loan_data['emp_length'].unique())
# Replacing all NaN with 0.
# Not sure, if this is the right way.
loan_data.loc[(loan_data['emp_length'] != '<1') & \
              (loan_data['emp_length'] != '1') & \
              (loan_data['emp_length'] != '2') & \
              (loan_data['emp_length'] != '3') & \
              (loan_data['emp_length'] != '4') & \
              (loan_data['emp_length'] != '5') & \
              (loan_data['emp_length'] != '6') & \
              (loan_data['emp_length'] != '7') & \
              (loan_data['emp_length'] != '8') & \
              (loan_data['emp_length'] != '9') & \
              (loan_data['emp_length'] != '10+'), 'emp_length'] = 0
print(loan_data['emp_length'].unique())

['10+' '<1' '1' '3' '8' '9' '4' '5' '6' '2' '7' nan]
['10+' '<1' '1' '3' '8' '9' '4' '5' '6' '2' '7' 0]


In [25]:
# Moving to home_ownership
loan_data['home_ownership'].unique()

array(['RENT', 'OWN', 'MORTGAGE', 'OTHER', 'NONE', 'ANY'], dtype=object)

In [26]:
# Though OTHER, NONE and ANY are a little confusing, I will do that cleaning later.
# For now things look ok.

# Printing all the columngs together again.
print(loan_data.iloc[:5,6:10])

  grade sub_grade emp_length home_ownership
0     B        B2        10+           RENT
1     C        C4         <1           RENT
2     C        C5        10+           RENT
3     C        C1        10+           RENT
4     B        B5          1           RENT


In [27]:
# Moving to next 6 columns
print(loan_data.iloc[:5,10:15])
for y in loan_data.columns[10:15]:
  print(y, loan_data[y].dtype)
loan_dict.loc[loan_dict['LoanStatNew'].isin(list(loan_data.columns.values[10:15]))]

  annual_inc verification_status issue_d  loan_status pymnt_plan
0      24000            Verified  Dec-11   Fully Paid          n
1      30000     Source Verified  Dec-11  Charged Off          n
2      12252        Not Verified  Dec-11   Fully Paid          n
3      49200     Source Verified  Dec-11   Fully Paid          n
4      80000     Source Verified  Dec-11   Fully Paid          n
annual_inc object
verification_status object
issue_d object
loan_status object
pymnt_plan object


LoanStatNew  \
4             annual_inc   
35               issue_d   
42           loan_status   
88            pymnt_plan   
112  verification_status   

                                                                                    Description  
4                 The self-reported annual income provided by the borrower during registration.  
35                                                          The month which the loan was funded  
42                                                                   Current status of the loan  
88                               Indicates if a payment plan has been put in place for the loan  
112  Indicates if income was verified by LC, not verified, or if the income source was verified

In [28]:
# Staring with annual_inc
# It should be numeric
# So, let'f find the non-numeric entry
df = loan_data['annual_inc'].to_frame().applymap(np.isreal) == False
df.loc[df['annual_inc'] == True]

annual_inc
0             True
1             True
2             True
3             True
4             True
5             True
6             True
7             True
8             True
9             True
10            True
11            True
12            True
13            True
14            True
15            True
16            True
17            True
18            True
19            True
20            True
21            True
22            True
23            True
24            True
25            True
26            True
27            True
28            True
29            True
...            ...
118618        True
118619        True
118620        True
118621        True
118622        True
118623        True
118624        True
118625        True
118626        True
118627        True
118628        True
118629        True
118630        True
118631        True
118632        True
118633        True
118634        True
118635        True
118636        True
118637        True
118638        True
118639        True
118640        True
118641        True
118642        True
118643        True
118644        True
118645        True
118646        True
118647        True

[1765404 rows x 1 columns]

In [29]:
# Looks like all the entries are considered non-integral
# Let's examine
loan_data['annual_inc'][:1]
# Since each object seems to string, convert it to numeric.
loan_data['annual_inc'] = pd.to_numeric(loan_data['annual_inc'])
# Find the non-numeric entry
df = loan_data['annual_inc'].to_frame().applymap(np.isreal) == False
df.loc[df['annual_inc'] == True]
df = loan_data['annual_inc']
df.loc[df.isnull()]
# So now the data for annual_inc is all good.

Series([], Name: annual_inc, dtype: float64)

In [30]:
# Now verification_status
loan_data['verification_status'].unique()

array(['Verified', 'Source Verified', 'Not Verified'], dtype=object)

In [31]:
# issue_d
loan_data['issue_d'].unique()

array(['Dec-11', 'Nov-11', 'Oct-11', 'Sep-11', 'Aug-11', 'Jul-11',
       'Jun-11', 'May-11', 'Apr-11', 'Mar-11', 'Feb-11', 'Jan-11',
       'Dec-10', 'Nov-10', 'Oct-10', 'Sep-10', 'Aug-10', 'Jul-10',
       'Jun-10', 'May-10', 'Apr-10', 'Mar-10', 'Feb-10', 'Jan-10',
       'Dec-09', 'Nov-09', 'Oct-09', 'Sep-09', 'Aug-09', 'Jul-09',
       'Jun-09', 'May-09', 'Apr-09', 'Mar-09', 'Feb-09', 'Jan-09',
       'Dec-08', 'Nov-08', 'Oct-08', 'Sep-08', 'Aug-08', 'Jul-08',
       'Jun-08', 'May-08', 'Apr-08', 'Mar-08', 'Feb-08', 'Jan-08',
       'Dec-07', 'Nov-07', 'Oct-07', 'Sep-07', 'Aug-07', 'Jul-07',
       'Jun-07', 'Dec-2013', 'Nov-2013', 'Oct-2013', 'Sep-2013',
       'Aug-2013', 'Jul-2013', 'Jun-2013', 'May-2013', 'Apr-2013',
       'Mar-2013', 'Feb-2013', 'Jan-2013', 'Dec-2012', 'Nov-2012',
       'Oct-2012', 'Sep-2012', 'Aug-2012', 'Jul-2012', 'Jun-2012',
       'May-2012', 'Apr-2012', 'Mar-2012', 'Feb-2012', 'Jan-2012',
       'Dec-2014', 'Nov-2014', 'Oct-2014', 'Sep-2014', 'Aug-2014

In [32]:
# loan_status
loan_data['loan_status'].unique()

array(['Fully Paid', 'Charged Off',
       'Does not meet the credit policy. Status:Fully Paid',
       'Does not meet the credit policy. Status:Charged Off', 'Current',
       'Late (16-30 days)', 'Late (31-120 days)', 'In Grace Period',
       'Default', 'Issued'], dtype=object)

In [33]:
# pymnt_plan
loan_data['pymnt_plan'].unique()

array(['n', 'y'], dtype=object)

In [34]:
# Moving to next 6 columns
# Dropping description out of hte list as it is pure text.
# Will see later, if adding it adds any value.
loan_data = loan_data.drop('desc', 1)
print(loan_data.iloc[:5,15:20])
for y in loan_data.columns[15:20]:
  print(y, loan_data[y].dtype)
loan_dict.loc[loan_dict['LoanStatNew'].isin(list(loan_data.columns.values[15:20]))]

  url         purpose                 title zip_code addr_state
0   0     credit_card              Computer    860xx         AZ
1   0             car                  bike    309xx         GA
2   0  small_business  real estate business    606xx         IL
3   0           other              personel    917xx         CA
4   0           other              Personal    972xx         OR
url object
purpose object
title object
zip_code object
addr_state object


LoanStatNew  \
2    addr_state   
87      purpose   
95        title   
111         url   
114    zip_code   

                                                                               Description  
2                               The state provided by the borrower in the loan application  
87                              A category provided by the borrower for the loan request.   
95                                                 The loan title provided by the borrower  
111                                                 URL for the LC page with listing data.  
114  The first 3 numbers of the zip code provided by the borrower in the loan application.

In [35]:
# url is the URL for the LC page with listing data.
# This data is not needed for our purpose
loan_data = loan_data.drop('url', 1)

In [36]:
# Let't check purpose
loan_data['purpose'].unique()

array(['credit_card', 'car', 'small_business', 'other', 'wedding',
       'debt_consolidation', 'home_improvement', 'major_purchase',
       'medical', 'moving', 'vacation', 'house', 'renewable_energy',
       'educational'], dtype=object)

In [38]:
# 'purpose' looks good.
# Let's try title
len(loan_data['title'].unique())

63150

In [39]:
# Again, 'title' is text entry which, for now, I am going to remove
loan_data = loan_data.drop('title', 1)

In [46]:
# zip_code
len(loan_data['zip_code'].unique())

int

In [51]:
# I am going to keep zip_code.
# The number of unique values are not too bad.
# Have to see how many zip_codes where missing and I replaced with 0.
len(loan_data.loc[loan_data['zip_code'] == 0])
# Since only one entry has the zip_code 0, I am going to randomly assign that item with one of the existing zip_codes.
# I hope, this won't affect things bad.
import random
loan_data.loc[(loan_data['zip_code'] == 0), 'zip_code'] =  random.choice(loan_data['zip_code'].unique())
len(loan_data.loc[loan_data['zip_code'] == 0])

0

In [52]:
# Moving to addr_state
loan_data['addr_state'].unique()

array(['AZ', 'GA', 'IL', 'CA', 'OR', 'NC', 'TX', 'VA', 'MO', 'CT', 'UT',
       'FL', 'NY', 'PA', 'MN', 'NJ', 'KY', 'OH', 'SC', 'RI', 'LA', 'MA',
       'WA', 'WI', 'AL', 'CO', 'KS', 'NV', 'AK', 'MD', 'WV', 'VT', 'MI',
       'DC', 'SD', 'NH', 'AR', 'NM', 'MT', 'HI', 'WY', 'OK', 'DE', 'MS',
       'TN', 'IA', 'NE', 'ID', 'IN', 'ME', 'ND'], dtype=object)

In [56]:
# Moving to next 6 columns
print(loan_data.iloc[:6,18:23])
for y in loan_data.columns[18:23]:
  print(y, loan_data[y].dtype)
loan_dict.loc[loan_dict['LoanStatNew'].isin(list(loan_data.columns.values[18:23]))]

     dti  delinq_2yrs earliest_cr_line  inq_last_6mths  mths_since_last_delinq
0  27.65            0           Jan-85               1                     0.0
1   1.00            0           Apr-99               5                     0.0
2   8.72            0           Nov-01               2                     0.0
3  20.00            0           Feb-96               1                    35.0
4  17.94            0           Jan-96               0                    38.0
5  11.20            0           Nov-04               3                     0.0
dti float64
delinq_2yrs int32
earliest_cr_line object
inq_last_6mths int32
mths_since_last_delinq float64


LoanStatNew  \
13             delinq_2yrs   
16                     dti   
18        earliest_cr_line   
32          inq_last_6mths   
50  mths_since_last_delinq   

                                                                                                                                                                                                 Description  
13                                                                                              The number of 30+ days past-due incidences of delinquency in the borrower's credit file for the past 2 years  
16  A ratio calculated using the borrower’s total monthly debt payments on the total debt obligations, excluding mortgage and the requested LC loan, divided by the borrower’s self-reported monthly income.  
18                                                                                                                                         The month the borrower's earliest reported credit line was opened  
32                                                                                                                          The number of inquiries in past 6 months (excluding auto and mortgage inquiries)  
50                                                                                                                                               The number of months since the borrower's last delinquency.

In [57]:
# dti is float, delinq_2yrs is int and inq_last_6mths is int.
# They look good.
# mts_since_last_delinq is float.
# Let's check it.
# Ideally, it should have been int
loan_data['mths_since_last_delinq'].unique()

array([  0.,  35.,  38.,  61.,   8.,  20.,  18.,  68.,  45.,  48.,  41.,
        40.,  74.,  25.,  53.,  39.,  10.,  26.,  56.,  77.,  28.,  52.,
        24.,  16.,  60.,  54.,  23.,   9.,  11.,  13.,  65.,  19.,  80.,
        22.,  59.,  79.,  44.,  64.,  57.,  14.,  63.,  49.,  15.,  73.,
        70.,  29.,  51.,   5.,  75.,  55.,   2.,  30.,  47.,  33.,  69.,
         4.,  43.,  21.,  27.,  46.,  81.,  78.,  82.,  31.,  76.,  62.,
        72.,  42.,  50.,   3.,  12.,  67.,  36.,  34.,  58.,  17.,  71.,
        66.,  32.,   6.,  37.,   7.,   1.,  83.,  86., 115.,  96., 103.,
       120., 106.,  89., 107.,  85.,  97.,  95., 110.,  84., 135.,  88.,
        87., 122.,  91., 146., 134., 114.,  99.,  93., 127., 101.,  94.,
       102., 129., 113., 139., 131., 156., 143., 109., 119., 149., 118.,
       130., 148., 126.,  90., 141., 116., 100., 152.,  98.,  92., 108.,
       133., 104., 111., 105., 170., 124., 136., 180., 188., 140., 151.,
       159., 121., 123., 157., 112., 154., 171., 14

In [61]:
# The data looks clean.
# I can safely convert it to int.
loan_data[['mths_since_last_delinq']] = loan_data[['mths_since_last_delinq']].astype(int)
loan_data['mths_since_last_delinq'].unique()

array([  0,  35,  38,  61,   8,  20,  18,  68,  45,  48,  41,  40,  74,
        25,  53,  39,  10,  26,  56,  77,  28,  52,  24,  16,  60,  54,
        23,   9,  11,  13,  65,  19,  80,  22,  59,  79,  44,  64,  57,
        14,  63,  49,  15,  73,  70,  29,  51,   5,  75,  55,   2,  30,
        47,  33,  69,   4,  43,  21,  27,  46,  81,  78,  82,  31,  76,
        62,  72,  42,  50,   3,  12,  67,  36,  34,  58,  17,  71,  66,
        32,   6,  37,   7,   1,  83,  86, 115,  96, 103, 120, 106,  89,
       107,  85,  97,  95, 110,  84, 135,  88,  87, 122,  91, 146, 134,
       114,  99,  93, 127, 101,  94, 102, 129, 113, 139, 131, 156, 143,
       109, 119, 149, 118, 130, 148, 126,  90, 141, 116, 100, 152,  98,
        92, 108, 133, 104, 111, 105, 170, 124, 136, 180, 188, 140, 151,
       159, 121, 123, 157, 112, 154, 171, 142, 125, 117, 176, 137, 145,
       158, 192, 132, 168, 195, 161, 128, 178, 160, 150, 202, 153, 138,
       162], dtype=int64)

In [66]:
# All looks good

# earliest_cr_line is type object, which is good.
loan_data['earliest_cr_line'].unique()

array(['Jan-85', 'Apr-99', 'Nov-01', ..., 'Nov-2014', 'Jun-1956',
       'Feb-1958'], dtype=object)

In [67]:
# Moving to next 6 columns
print(loan_data.iloc[:6,23:28])
for y in loan_data.columns[23:28]:
  print(y, loan_data[y].dtype)
loan_dict.loc[loan_dict['LoanStatNew'].isin(list(loan_data.columns.values[23:28]))]

   mths_since_last_record  open_acc  pub_rec  revol_bal revol_util
0                     0.0         3        0      13648     83.70%
1                     0.0         3        0       1687      9.40%
2                     0.0         2        0       2956     98.50%
3                     0.0        10        0       5598        21%
4                     0.0        15        0      27783     53.90%
5                     0.0         9        0       7963     28.30%
mths_since_last_record float64
open_acc int32
pub_rec int32
revol_bal int32
revol_util object


LoanStatNew  \
52  mths_since_last_record   
73                open_acc   
85                 pub_rec   
90               revol_bal   
91              revol_util   

                                                                                                                   Description  
52                                                                          The number of months since the last public record.  
73                                                              The number of open credit lines in the borrower's credit file.  
85                                                                                         Number of derogatory public records  
90                                                                                              Total credit revolving balance  
91  Revolving line utilization rate, or the amount of credit the borrower is using relative to all available revolving credit.

In [68]:
# Start analyzing mths_since_last_record
loan_data['mths_since_last_record'].unique()

array([  0., 113., 105.,  97.,  33.,  93.,  52.,  85.,  90.,  91., 114.,
        92., 117.,  87.,  45.,  83., 118.,  38., 101., 100., 112., 110.,
        88.,  79.,  77., 107., 102.,  98.,  95., 103.,  96., 116., 111.,
        89., 108.,  29., 106., 115.,  53.,  86.,  57.,  63.,  94., 109.,
        99., 104.,  76.,  61.,  28.,  23.,  75.,  47.,  82.,  21.,  62.,
        44.,  80.,  67., 119.,  42.,  34.,  66.,  58.,  22.,  56.,  72.,
        64.,  50.,  69.,  49.,  74.,  35.,  12.,  26.,  78.,  54.,  37.,
        73.,  11.,  31.,  59.,  32.,  81.,  68.,  55.,  39.,  51.,  70.,
        30.,  41.,  71.,  40.,  43.,  27.,  65.,  46.,  19.,  17.,  25.,
        13.,  48.,  36.,   7.,  60.,  14.,   6.,  18.,  20., 120., 129.,
         5.,  24.,  15.,  84.,  10.,  16.,   8.,   9.,   3., 121.,   4.,
         1.,   2.])

In [69]:
# Look good and all of them are integers (as there are no partial months).
# Hence, converting all of them to int
loan_data[['mths_since_last_record']] = loan_data[['mths_since_last_record']].astype(int)
loan_data['mths_since_last_record'].unique()

array([  0, 113, 105,  97,  33,  93,  52,  85,  90,  91, 114,  92, 117,
        87,  45,  83, 118,  38, 101, 100, 112, 110,  88,  79,  77, 107,
       102,  98,  95, 103,  96, 116, 111,  89, 108,  29, 106, 115,  53,
        86,  57,  63,  94, 109,  99, 104,  76,  61,  28,  23,  75,  47,
        82,  21,  62,  44,  80,  67, 119,  42,  34,  66,  58,  22,  56,
        72,  64,  50,  69,  49,  74,  35,  12,  26,  78,  54,  37,  73,
        11,  31,  59,  32,  81,  68,  55,  39,  51,  70,  30,  41,  71,
        40,  43,  27,  65,  46,  19,  17,  25,  13,  48,  36,   7,  60,
        14,   6,  18,  20, 120, 129,   5,  24,  15,  84,  10,  16,   8,
         9,   3, 121,   4,   1,   2], dtype=int64)

In [70]:
# Start analyzing open_acc
loan_data['open_acc'].unique()

array([ 3,  2, 10, 15,  9,  7,  4, 11, 14, 12, 20,  8,  6, 17,  5, 13, 16,
       30, 21, 18, 19, 27, 23, 34, 25, 22, 24, 26, 32, 28, 29, 33, 31, 39,
       35, 36, 38, 44, 41, 42,  1, 46, 37, 47,  0, 40, 45, 49, 53, 51, 43,
       62, 48, 50, 52, 54, 76, 58, 55, 84, 75, 61, 65, 67, 57, 66, 68, 70,
       60, 56, 82, 63, 59, 64, 79, 74, 90, 72, 81, 77, 71, 69, 80, 86, 97,
       88, 93, 91], dtype=int64)

In [71]:
# Start analyzing pub_rec
loan_data['pub_rec'].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  9,  8,  7, 11, 49, 10, 54, 12, 18, 19,
       16, 15, 14, 40, 63, 13, 21, 34, 17, 23, 26, 28, 20, 86, 22, 46, 37,
       31, 47, 24, 45, 25, 61, 32, 44], dtype=int64)

In [77]:
# Start analyzing revol_bal
loan_data['revol_bal'].unique()

array([ 13648,   1687,   2956, ..., 196098, 171520,  64696], dtype=int64)

In [80]:
# Start analyzing revol_util
# All revol_util are described in terms of %.
# So, a simple replacement should work.
loan_data['revol_util'] = loan_data['revol_util'].str.replace("%","")
# Now convert all of them to numeric
loan_data['revol_util'] = pd.to_numeric(loan_data['revol_util'])
# Find the non-numeric entry
df = loan_data['revol_util'].to_frame().applymap(np.isreal) == False
df.loc[df['revol_util'] == True]
# The revol_util data looks all good.

Empty DataFrame
Columns: [revol_util]
Index: []

In [81]:
# Moving to next 5 columns
print(loan_data.iloc[:6,28:33])
for y in loan_data.columns[28:33]:
  print(y, loan_data[y].dtype)
loan_dict.loc[loan_dict['LoanStatNew'].isin(list(loan_data.columns.values[28:33]))]

   total_acc initial_list_status  out_prncp  out_prncp_inv   total_pymnt
0          9                   f        0.0            0.0   5863.155187
1          4                   f        0.0            0.0   1014.530000
2         10                   f        0.0            0.0   3005.666844
3         37                   f        0.0            0.0  12231.890000
4         38                   f        0.0            0.0   4066.908161
5         12                   f        0.0            0.0   5632.210000
total_acc int32
initial_list_status object
out_prncp float64
out_prncp_inv float64
total_pymnt float64


LoanStatNew  \
29   initial_list_status   
80             out_prncp   
81         out_prncp_inv   
99             total_acc   
105          total_pymnt   

                                                                         Description  
29                The initial listing status of the loan. Possible values are – W, F  
80                           Remaining outstanding principal for total amount funded  
81   Remaining outstanding principal for portion of total amount funded by investors  
99          The total number of credit lines currently in the borrower's credit file  
105                                Payments received to date for total amount funded

In [82]:
# Start analyzing total_acc
loan_data['total_acc'].unique()

array([  9,   4,  10,  37,  38,  12,  11,  13,   3,  23,  34,  29,  28,
        42,  14,  22,  21,  17,   7,  31,  44,  26,  16,   6,  18,  27,
        24,  25,  40,  35,   8,  20,  15,  19,  36,  51,  32,  30,  33,
        46,   5,  61,  56,  50,  41,  39,  79,  62,  43,  47,  53,  45,
        60,  55,  52,  58,  54,  57,  49,  63,  48,  59,  77,  87,  75,
        72,  64,  67,  78,  76,  74,  66,  81,  90,  80,  71,  69,  73,
        70,  68,  65,   2,   1,   0, 105,  83,  84,  98,  88,  82,  91,
        99,  86,  93,  92,  96, 101, 150,  95,  85,  89, 156, 106,  97,
       119, 124, 100,  94, 121, 102, 117, 116, 118, 111, 127, 112, 125,
       110, 109, 135, 104, 151, 130, 107, 113, 169, 140, 146, 129, 126,
       137, 103, 138, 162, 114, 108, 176, 115, 173, 120, 133, 160, 157,
       144, 122, 136, 141, 123, 165], dtype=int64)

In [83]:
# Start analyzing initial_list_status
loan_data['initial_list_status'].unique()

array(['f', 'w'], dtype=object)

In [84]:
# Start analyzing out_prncp
loan_data['out_prncp'].unique()

array([    0.  ,  5496.76,  2861.71, ..., 13463.07, 17546.03, 17738.59])

In [85]:
# Start analyzing out_prncp_inv
loan_data['out_prncp_inv'].unique()

array([    0.  ,  5496.76,  2861.71, ..., 33956.55, 17546.03, 17738.59])

In [86]:
# Want to see if the out_prncp and out_prncp_inv are ever different
df_ = loan_data['out_prncp'] - loan_data['out_prncp_inv'] != 0
df = df_.to_frame()
print(len(df.loc[df[0] == True]))

45216


In [87]:
# Since, there is a non-zero number of cases where the the out_prncp and out_prncp_inv are different, I am keeping it.
# Though, 45K entries out of 1.7million seems small.o

# Start analyzing total_pymnt
loan_data['total_pymnt'].unique()

array([ 5863.155187,  1014.53    ,  3005.666844, ..., 25027.67375 ,
        1672.64    ,   605.72    ])

In [90]:
# Moving to next 4 columns
print(loan_data.iloc[:6,33:37])
for y in loan_data.columns[33:37]:
  print(y, loan_data[y].dtype)
loan_dict.loc[loan_dict['LoanStatNew'].isin(list(loan_data.columns.values[33:37]))]

   total_pymnt_inv  total_rec_prncp  total_rec_int  total_rec_late_fee
0          5833.84          5000.00         863.16                0.00
1          1014.53           456.46         435.17                0.00
2          3005.67          2400.00         605.67                0.00
3         12231.89         10000.00        2214.92               16.97
4          4066.91          3000.00        1066.91                0.00
5          5632.21          5000.00         632.21                0.00
total_pymnt_inv float64
total_rec_prncp float64
total_rec_int float64
total_rec_late_fee float64


LoanStatNew  \
106     total_pymnt_inv   
107       total_rec_int   
108  total_rec_late_fee   
109     total_rec_prncp   

                                                                   Description  
106  Payments received to date for portion of total amount funded by investors  
107                                                  Interest received to date  
108                                                 Late fees received to date  
109                                                 Principal received to date